window.DUODECIMA_GODS = [
  // Base canônica sincronizada com o Guia da Duodécima · 04/09/2026
  {id:"iuppiter",name:"Iuppiter Optimus Maximus",group:"Triunviro",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:25,hpPerDecade:5,bonuses:{"fe": 2, "for": 1},skillChoice:["Intimidação", "Atletismo"],resource:{name:"Raiva do Trovão",maxFormula:"8 + floor(nível/10)",max:(lvl)=>8+Math.floor(lvl/10)},notes:["A ficha usa exatamente as bonificações escritas no Guia consolidado atual."]},
  {id:"netuno",name:"Netuno",group:"Triunviro",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:25,hpPerDecade:5,bonuses:{"des": 2, "fe": 1, "car": 1},skillChoice:["Acrobacia", "Atletismo"],resource:{name:"Maré Crescente",maxFormula:"10",max:(lvl)=>10}},
  {id:"plutao",name:"Plutão",group:"Triunviro",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:25,hpPerDecade:5,bonuses:{"con": 2, "fe": 1, "car": 1},skillChoice:["Intimidação", "Intuição"],resource:{name:"Acúmulo Necromântico",maxFormula:"10",max:(lvl)=>10}},
  {id:"summanus",name:"Summanus",group:"Triunviro",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:22,hpPerDecade:4,bonuses:{"int": 2, "fe": 1, "des": 1},skillChoice:["Intimidação", "Furtividade"],resource:{name:"Carga Noturna",maxFormula:"10",max:(lvl)=>10}},
  {id:"vulcano",name:"Vulcano",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"int",hpBase:33,hpPerDecade:5,bonuses:{"con": 2, "for": 1},grantedSkills:["Tolerância"]},
  {id:"baco",name:"Baco",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "des": 1},grantedSkills:["Tolerância"]},
  {id:"vesta",name:"Vesta",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:25,hpPerDecade:6,bonuses:{"for": 2, "con": 1},grantedSkills:["Tolerância"]},
  {id:"mercurio",name:"Mercúrio",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"des",hpBase:20,hpPerDecade:5,bonuses:{"des": 2, "car": 1},grantedSkills:["Mãos Leves"]},
  {id:"febo",name:"Febo",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "fe": 1},skillChoice:["Atuação", "Manipulação", "Intimidação", "Persuasão"]},
  {id:"venus",name:"Vênus",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "des": 1},grantedSkills:["Persuasão"]},
  {id:"marte",name:"Marte Ultor",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"con",hpBase:25,hpPerDecade:6,bonuses:{"for": 2, "con": 1},grantedSkills:["Atletismo"]},
  {id:"diana",name:"Diana",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"des": 2, "con": 1},grantedSkills:["Agilidade"]},
  {id:"ceres",name:"Ceres",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:25,hpPerDecade:5,bonuses:{"con": 2, "fe": 1},grantedSkills:["Natureza"]},
  {id:"juno",name:"Juno Mater",group:"Dii Consentis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "car": 1},grantedSkills:["Intuição"]},
  {id:"fobetor",name:"Fobetor",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"con": 2, "car": 1},grantedSkills:["Intimidação"],resource:{name:"Desesperança",maxFormula:"5 + floor(nível/10)",max:(lvl)=>5+Math.floor(lvl/10)}},
  {id:"somnos",name:"Somnos",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "int": 1},grantedSkills:["Conhecimento Mítico"]},
  {id:"somnia",name:"Somnia",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "des": 1},grantedSkills:["Manipulação"],resource:{name:"Esperança Dourada",maxFormula:"5 + floor(nível/10)",max:(lvl)=>5+Math.floor(lvl/10)}},
  {id:"fantaso",name:"Fântaso",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "fe": 1},grantedSkills:["Intuição"]},
  {id:"letum",name:"Letum",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:25,hpPerDecade:5,bonuses:{"for": 2, "car": 1},grantedSkills:["Intimidação"],resource:{name:"Ruína",maxFormula:"5",max:(lvl)=>5}},
  {id:"trivia",name:"Trivia",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"int",hpBase:20,hpPerDecade:5,bonuses:{"int": 2, "fe": 1},grantedSkills:["Conhecimento Mágico"],notes:["Trivia só tem filhas mulheres."]},
  {id:"libitina",name:"Libitina",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "con": 1},grantedSkills:["Conhecimento Religioso"]},
  {id:"laverna",name:"Laverna",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "car": 1},grantedSkills:["Conhecimento Mágico"]},
  {id:"proserpina",name:"Proserpina",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "con": 1},grantedSkills:["Natureza"]},
  {id:"mors",name:"Mors",group:"Dii Inferi",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "con": 1},grantedSkills:["Furtividade"],notes:["Tocados por Mors não são filhos diretos: a relação é uma marca recebida no nascimento."]},
  {id:"bellona",name:"Bellona",group:"Alati",source:'Guia consolidado · 04/09/2026',casting:"con",hpBase:25,hpPerDecade:7,bonuses:{"for": 2, "con": 1},grantedSkills:["Atletismo"]},
  {id:"vis",name:"Vis",group:"Alati",source:'Guia consolidado · 04/09/2026',casting:"for",hpBase:30,hpPerDecade:5,bonuses:{"for": 2, "con": 1},resource:{name:"Imperium",maxFormula:"10 (barra coletiva Alati)",max:(lvl)=>10}},
  {id:"victoria",name:"Victoria",group:"Alati",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:25,hpPerDecade:5,bonuses:{"des": 2, "car": 1},skillChoice:["Agilidade", "Intimidação"],resource:{name:"Imperium",maxFormula:"10 (barra coletiva Alati)",max:(lvl)=>10}},
  {id:"aemulatio",name:"Aemulatio",group:"Alati",source:'Guia consolidado · 04/09/2026',casting:"int",hpBase:25,hpPerDecade:5,bonuses:{"int": 2, "con": 1},skillChoice:["Percepção", "Estratégia"],resource:{name:"Imperium",maxFormula:"10 (barra coletiva Alati)",max:(lvl)=>10}},
  {id:"potestas",name:"Potestas",group:"Alati",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:25,hpPerDecade:5,bonuses:{"car": 2, "int": 1},grantedSkills:["Intimidação"],resource:{name:"Imperium",maxFormula:"10 (barra coletiva Alati)",max:(lvl)=>10}},
  {id:"aeolos",name:"Aeolos",group:"Ventis",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "int": 1},grantedSkills:["Persuasão"],notes:["Aeolos integra o grupo Ventis no Guia consolidado, mas o próprio kit não possui a passiva Dança dos Ventos."]},
  {id:"aquilon",name:"Aquilon",group:"Ventis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"des": 2, "con": 1},grantedSkills:["Intimidação"],resource:{name:"Dança dos Ventos",maxFormula:"20 (barra coletiva)",max:(lvl)=>20}},
  {id:"auster",name:"Auster",group:"Ventis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"des": 2, "for": 1},grantedSkills:["Tolerância"],resource:{name:"Dança dos Ventos",maxFormula:"20 (barra coletiva)",max:(lvl)=>20}},
  {id:"favonio",name:"Favônio",group:"Ventis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"des": 2, "car": 1},grantedSkills:["Natureza"],resource:{name:"Dança dos Ventos",maxFormula:"20 (barra coletiva)",max:(lvl)=>20}},
  {id:"vulturnos",name:"Vulturnos",group:"Ventis",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"des": 2, "fe": 1},grantedSkills:["Intimidação"],resource:{name:"Dança dos Ventos",maxFormula:"20 (barra coletiva)",max:(lvl)=>20}},
  {id:"metus",name:"Metus",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "con": 1},grantedSkills:["Intimidação"],resource:{name:"Tensão",maxFormula:"4",max:(lvl)=>4}},
  {id:"timor",name:"Timor",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"for": 2, "car": 1},grantedSkills:["Intimidação"]},
  {id:"angerona",name:"Angerona",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"int": 2, "fe": 1},grantedSkills:["Percepção"]},
  {id:"fama",name:"Fama",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "int": 1},grantedSkills:["Conhecimento Histórico"]},
  {id:"arcus",name:"Arcus",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "des": 1},grantedSkills:["Etiqueta"]},
  {id:"justitia",name:"Justitia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "int": 1},grantedSkills:["Intuição"]},
  {id:"invidia",name:"Invidia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "int": 1},grantedSkills:["Enganação"]},
  {id:"discordia",name:"Discórdia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "int": 1},grantedSkills:["Manipulação"]},
  {id:"fortuna",name:"Fortuna",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2},skillBonuses:{"Agilidade": 1},grantedSkills:["Mãos Leves"]},
  {id:"concordia",name:"Concordia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "fe": 1},grantedSkills:["Persuasão"]},
  {id:"angitia",name:"Angitia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "con": 1},grantedSkills:["Medicina"]},
  {id:"juventas",name:"Juventas",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"con": 2, "fe": 1},grantedSkills:["Medicina"]},
  {id:"cupido-inanis",name:"Cupido Inanis",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:18,hpPerDecade:4,bonuses:{"car": 2, "int": 1},grantedSkills:["Manipulação"]},
  {id:"jano",name:"Jano",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"int",hpBase:20,hpPerDecade:5,bonuses:{"int": 2, "fe": 1},grantedSkills:["Intuição"]},
  {id:"laetitia",name:"Laetitia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"car",hpBase:20,hpPerDecade:5,bonuses:{"car": 2, "des": 1},grantedSkills:["Atuação"]},
  {id:"cimopoleia",name:"Cimopoleia",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"fe": 2, "con": 1},skillChoice:["Sobrevivência", "Intimidação"],notes:["Filhos de Cimopoleia são considerados criaturas monstruosas."]},
  {id:"silvano",name:"Protegidos de Silvano",group:"Numina",source:'Guia consolidado · 04/09/2026',casting:"fe",hpBase:20,hpPerDecade:5,bonuses:{"con": 2, "fe": 1},grantedSkills:["Sobrevivência"],notes:["Protegidos de Silvano são ninfas ou espíritos silvestres."]}
];

window.DUODECIMA_EXCLUDED_GODS = [
  {name:'Minerva',reason:'Sem kit no Guia consolidado atual.'}
];
