(()=>{
  'use strict';
  const STORAGE_KEY='duodecima_universal_stage4_v24';
  let queued=false;

  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function readSheet(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||{}}catch(_){return {}}}
  function sanityInfo(v){const s=Math.max(0,Math.min(100,Number(v)||0));if(s===0)return {key:'louco',name:'Louco',range:'0',tone:'danger',auto:'',text:'Perda permanente do personagem.'};if(s<=20)return {key:'beira',name:'À Beira da Loucura',range:'20–1',tone:'danger',auto:'INT −5 · CAR −5 · FÉ −3',text:'Falha automática contra ficar Abalado ou Apavorado. No início do turno, faça um teste de Fé DT 15; em falha, não pode agir. Mantém as penalidades mentais do estágio Abalado.'};if(s<=40)return {key:'abalado',name:'Abalado',range:'40–21',tone:'orange',auto:'INT −5 · CAR −5 · FÉ −3',text:'−5 em Inteligência e Carisma; −3 em testes de Fé. Ataques que explorem medo causam dano dobrado à Sanidade.'};if(s<=70)return {key:'instavel',name:'Instável',range:'70–41',tone:'warn',auto:'INT −2 · CAR −2',text:'−2 em Inteligência, Carisma e testes ligados à lógica ou concentração.'};return {key:'estavel',name:'Estável',range:'100–71',tone:'good',auto:'',text:'Sem penalidades.'}}

  function styles(){if(document.querySelector('#qol-v5171-styles'))return;const s=document.createElement('style');s.id='qol-v5171-styles';s.textContent=`
    .qol-rest-strip{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px;margin:0 0 12px;border:1px solid color-mix(in srgb,var(--accent) 22%,var(--line));border-radius:12px;background:color-mix(in srgb,var(--accent) 4%,var(--panel));box-shadow:none}.qol-rest-copy{display:flex;align-items:baseline;gap:8px}.qol-rest-copy b{font-size:12px}.qol-rest-copy small{color:var(--muted);font-size:10px}.qol-rest-actions{display:flex;gap:7px;flex-wrap:wrap}.qol-rest-actions button{min-height:30px;padding:6px 10px;font-size:11px}
    .qol-sanity-card{display:grid;grid-template-columns:minmax(150px,.48fr) minmax(0,1.52fr);gap:12px;align-items:center;padding:11px 13px;margin:0 0 12px;border:1px solid var(--line);border-left:4px solid var(--accent);border-radius:12px;background:var(--panel)}.qol-sanity-card[data-tone="good"]{border-left-color:#4bc46b}.qol-sanity-card[data-tone="warn"]{border-left-color:#e0b43e}.qol-sanity-card[data-tone="orange"]{border-left-color:#ed802f}.qol-sanity-card[data-tone="danger"]{border-left-color:#e23a50}.qol-sanity-head{display:flex;align-items:center;gap:9px}.qol-sanity-value{font:800 20px/1 system-ui,sans-serif}.qol-sanity-name{display:flex;flex-direction:column}.qol-sanity-name b{font-size:12px}.qol-sanity-name small{font-size:9px;color:var(--muted);letter-spacing:.06em;text-transform:uppercase}.qol-sanity-effect{font-size:11px;line-height:1.45}.qol-sanity-effect small{display:block;margin-top:3px;color:var(--muted);font-size:9px}.qol-sanity-auto{display:inline-block;margin-right:6px;padding:2px 6px;border:1px solid color-mix(in srgb,var(--accent) 24%,var(--line));border-radius:999px;font-size:9px;font-weight:800;background:color-mix(in srgb,var(--accent) 7%,transparent)}.qol-effective-attr{color:var(--accent)!important}.qol-effective-attr:after{content:' SAN';margin-left:4px;font-size:7px;vertical-align:top;color:var(--muted);letter-spacing:.08em}
    .qol-reset-dialog{width:min(500px,calc(100vw - 28px));padding:0;border:1px solid var(--line);border-radius:16px;background:var(--panel);color:var(--text);box-shadow:0 26px 90px #000a}.qol-reset-dialog::backdrop{background:#000b;backdrop-filter:blur(3px)}.qol-reset-card{padding:20px}.qol-reset-card h2{margin:2px 0 8px}.qol-reset-warning{margin:14px 0;padding:12px;border:1px solid color-mix(in srgb,#e0b43e 36%,var(--line));border-radius:10px;background:color-mix(in srgb,#e0b43e 8%,transparent);font-size:12px;line-height:1.5}.qol-reset-question{font-weight:800;margin:14px 0 4px}.qol-reset-actions{display:flex;gap:8px;margin-top:18px;flex-wrap:wrap}.qol-reset-actions .qol-reset-final{margin-left:auto}
    @media(max-width:680px){.qol-rest-strip{align-items:flex-start;flex-direction:column}.qol-sanity-card{grid-template-columns:1fr}.qol-reset-actions{flex-direction:column}.qol-reset-actions button{width:100%}.qol-reset-actions .qol-reset-final{margin-left:0}}
  `;document.head.appendChild(s)}

  function resetDialog(){let d=document.querySelector('#qolResetDialog');if(d)return d;d=document.createElement('dialog');d.id='qolResetDialog';d.className='qol-reset-dialog';d.innerHTML=`<div class="qol-reset-card"><p class="eyebrow">NOVA FICHA</p><h2>Resetar ficha</h2><div class="qol-reset-warning"><b>Salve seu personagem antes de continuar.</b><br>Antes de resetar a ficha, recomendamos exportar o JSON atual. Assim você poderá importar este personagem novamente no futuro sem perder os dados.</div><p class="qol-reset-question">Tem certeza de que deseja resetar a ficha?</p><p class="muted compact">Esta ação salva a ficha atual em Backups e abre uma ficha nova para criação.</p><div class="qol-reset-actions"><button type="button" class="ghost" data-qol-export>Exportar JSON agora</button><button type="button" class="ghost" data-qol-cancel>Cancelar</button><button type="button" class="danger qol-reset-final" data-qol-confirm>Sim, resetar</button></div></div>`;document.body.appendChild(d);d.querySelector('[data-qol-cancel]').onclick=()=>d.close();d.querySelector('[data-qol-export]').onclick=()=>document.querySelector('#exportBtn')?.click();d.querySelector('[data-qol-confirm]').onclick=async()=>{const btn=document.querySelector('#resetBtn'),handler=btn?.onclick;if(typeof handler!=='function'){console.error('[Ficha] Handler original de reset não encontrado.');return}d.close();const originalConfirm=window.confirm;try{window.confirm=()=>true;await handler.call(btn,new Event('click'))}catch(err){console.error('[Ficha] Falha ao resetar ficha.',err)}finally{window.confirm=originalConfirm}};d.addEventListener('click',e=>{if(e.target===d)d.close()});return d}
  function resetIntercept(){if(document.documentElement.dataset.qolReset==='1')return;document.documentElement.dataset.qolReset='1';document.addEventListener('click',e=>{if(!e.target?.closest?.('#resetBtn'))return;e.preventDefault();e.stopImmediatePropagation();const d=resetDialog();d.showModal?d.showModal():d.setAttribute('open','')},true)}

  function moveRests(){const status=document.querySelector('[data-pane="status"]'),combat=document.querySelector('[data-pane="combat"]');if(!status||!combat)return;const a=combat.querySelector('#shortRest'),b=combat.querySelector('#longRest');if(!a||!b)return;let strip=status.querySelector('.qol-rest-strip');if(!strip){strip=document.createElement('article');strip.className='qol-rest-strip';strip.innerHTML='<div class="qol-rest-copy"><b>Descansos</b><small>Curto: +25 HP / +150 EN · Longo: HP e EN completos</small></div><div class="qol-rest-actions"></div>';const anchor=status.querySelector('.overview-grid')||status.firstElementChild;anchor?status.insertBefore(strip,anchor):status.prepend(strip)}strip.querySelector('.qol-rest-actions').append(a,b);const card=combat.querySelector('.combat-rest-card');if(card){const eyebrow=card.querySelector('.eyebrow');if(eyebrow&&eyebrow.textContent!=='MODS DE COMBATE')eyebrow.textContent='MODS DE COMBATE';card.querySelector('.subcard.compact')?.remove()}}

  function sanityCard(scope,info,san,signature){const c=document.createElement('article');c.className='qol-sanity-card';c.dataset.qolSanity=scope;c.dataset.tone=info.tone;c.dataset.signature=signature;const auto=info.auto?`<span class="qol-sanity-auto">automático · ${esc(info.auto)}</span>`:'';c.innerHTML=`<div class="qol-sanity-head"><strong class="qol-sanity-value">${san}</strong><div class="qol-sanity-name"><b>${esc(info.name)}</b><small>${esc(info.range)} de Sanidade</small></div></div><div class="qol-sanity-effect">${auto}${esc(info.text)}<small>As penalidades numéricas de atributos são aplicadas automaticamente aos cálculos da ficha.</small></div>`;return c}
  function refreshSanity(){const st=readSheet(),san=Math.max(0,Math.min(100,Number(st.currentSanity??100))),info=sanityInfo(san),sig=`${san}:${info.key}`;for(const [scope,pane] of [['status',document.querySelector('[data-pane="status"]')],['combat',document.querySelector('[data-pane="combat"]')]]){if(!pane)continue;const old=pane.querySelector(`.qol-sanity-card[data-qol-sanity="${scope}"]`);if(!old){const c=sanityCard(scope,info,san,sig),rest=scope==='status'?pane.querySelector('.qol-rest-strip'):null,anchor=rest?.nextElementSibling||pane.querySelector(scope==='status'?'.overview-grid':'.target-resource-zone, .combat-command-grid');anchor?pane.insertBefore(c,anchor):pane.prepend(c)}else if(old.dataset.signature!==sig)old.replaceWith(sanityCard(scope,info,san,sig))}document.querySelectorAll('.core-san .core-stat-caption').forEach(x=>{if(x.textContent!==info.name)x.textContent=info.name});document.querySelectorAll('.combat-quick-values>div').forEach(row=>{if(row.querySelector('span')?.textContent?.trim()==='Sanidade'){const v=row.querySelector('b');if(v&&v.textContent!==info.name)v.textContent=info.name}});document.querySelectorAll('.attr').forEach(card=>{const m=(card.querySelector('.attr-break')?.textContent||'').match(/efetivo\s+([−-]?\d+)/i),total=card.querySelector('.attr-total');if(m&&total){const v=m[1].replace('−','-');if(total.textContent!==v)total.textContent=v;total.classList.add('qol-effective-attr')}})}

  function refresh(){styles();resetDialog();moveRests();refreshSanity()}
  function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;refresh()})}
  function init(){styles();resetIntercept();refresh();const root=document.querySelector('#sheetView')||document.body;new MutationObserver(queue).observe(root,{childList:true,subtree:true});window.addEventListener('storage',queue)}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
