window.DUODECIMA_SKILLS = [
  {name:"Atletismo",attr:"for"},
  {name:"Acrobacia",attr:"des"},
  {name:"Furtividade",attr:"des"},
  {name:"Mãos Leves",attr:"des"},
  {name:"Agilidade",attr:"des"},
  {name:"Tolerância",attr:"con"},
  {name:"Investigação",attr:"int"},
  {name:"Natureza",attr:"int"},
  {name:"Medicina",attr:"int"},
  {name:"Sobrevivência",attr:"int"},
  {name:"Conhecimento Histórico",attr:"int"},
  {name:"Conhecimento Mítico",attr:"int"},
  {name:"Guerra",attr:"int"},
  {name:"Ofício",attr:"int"},
  {name:"Estratégia",attr:"int"},
  {name:"Conhecimento Religioso",attr:"fe"},
  {name:"Conhecimento Mágico",attr:"fe"},
  {name:"Intuição",attr:"fe"},
  {name:"Percepção",attr:"fe"},
  {name:"Adestrar Animais",attr:"fe"},
  {name:"Etiqueta",attr:"car"},
  {name:"Atuação",attr:"car"},
  {name:"Manipulação",attr:"car"},
  {name:"Intimidação",attr:"car"},
  {name:"Persuasão",attr:"car"},
  {name:"Enganação",attr:"car"}
];
