window.DUODECIMA_TALENTS = [
  {id:'ataque-extra',name:'Ataque Extra',minLevel:30,description:'Ao realizar um ataque, você pode fazer um ataque a mais. A narração fica a seu critério: podem ser dois cortes com a espada, personalização de armas ou apenas ataques rápidos.',repeatable:false},
  {id:'expert',name:'Expert',minLevel:1,description:'Escolha uma perícia. Seu bônus de proficiência é dobrado ao exercê-la.',repeatable:true,params:['skill']},
  {id:'perito',name:'Perito',minLevel:1,description:'Ganha três novas perícias.',repeatable:true,params:['skill1','skill2','skill3']},
  {id:'defensor',name:'Defensor',minLevel:1,description:'Você recebe +1 nos seus dados de Defesa e Resistência.',repeatable:true,automation:'defense'},
  {id:'comandante',name:'Comandante',minLevel:30,description:'Uma vez por turno, ao realizar um ataque, você faz com que um aliado à sua escolha possa realizar um ataque contra o mesmo alvo. O aliado precisa ser capaz de atingir o alvo com a arma que está usando.',repeatable:false},
  {id:'lingua-de-prata',name:'Língua de Prata',minLevel:1,description:'Você ganha +2 em embates diplomáticos, podendo somar esse bônus a perícias de Carisma quando aplicável.',repeatable:true,manual:true},
  {id:'interceptador',name:'Interceptador',minLevel:1,description:'Uma vez por rodada, pode reduzir 1d8 + seu bônus de proficiência do dano recebido por você ou por um aliado próximo. Você precisa estar empunhando uma arma corpo a corpo ou um escudo.',repeatable:false},
  {id:'duelista',name:'Duelista',minLevel:1,description:'Se está usando uma arma e nenhum escudo, soma +2 ao dano.',repeatable:false},
  {id:'campeao',name:'Campeão',minLevel:1,description:'Sua margem de acerto crítico reduz em 1.',repeatable:true},
  {id:'sortudo',name:'Sortudo',minLevel:1,description:'Pode rerrolar um dado 2 vezes por cena.',repeatable:false},
  {id:'inspirado',name:'Inspirado',minLevel:1,description:'Uma vez por turno, pode adicionar 1d6 a uma rolagem de d20. Você pode escolher usar depois de ver a rolagem, mas antes do resultado do teste ser narrado.',repeatable:false},
  {id:'curandeiro',name:'Curandeiro',minLevel:1,description:'Quando você cura algo ou alguém, a cura aumenta com o nível: +2 nos níveis 0–40; +4 nos níveis 41–80; +6 nos níveis 81–90; +10 nos níveis 91+.',repeatable:true,manual:true},
  {id:'querido',name:'Querido',minLevel:60,description:'Quando você buffa um aliado, esse buff dura um turno a mais antes de se dissipar.',repeatable:true},
  {id:'chato',name:'Chato',minLevel:60,description:'Sempre que você causar um debuff, aumenta em +1 a penalidade sofrida pela condição ou efeito.',repeatable:true},
  {id:'beijo-fortuna',name:'Beijo de Fortuna',minLevel:1,description:'Você é imune a falhas críticas. Sempre que rolar um 1 natural, considera uma rolagem de 2.',repeatable:true},
  {id:'adepto-elemental',name:'Adepto Elemental',minLevel:1,description:'Escolha um elemento, como fogo, água, raios ou ventos. Quando causar dano do elemento escolhido, causa +2 de dano. Pode escolher este talento novamente desde que selecione elementos diferentes.',repeatable:true,params:['element']},
  {id:'resiliente',name:'Resiliente',minLevel:1,description:'Escolha um atributo. Você pode adicionar seu bônus de proficiência nas rolagens de Resistência desse atributo. Isso vale apenas para testes puros de Resistência, não para perícias, ataques ou Defesa.',repeatable:true,params:['attribute']},
  {id:'bruto',name:'Bruto',minLevel:1,description:'Você pode substituir Destreza por Constituição ao realizar jogadas de Defesa.',repeatable:true,automation:'defense-constitution'},
  {id:'agil',name:'Ágil',minLevel:1,description:'Você adiciona metade do seu bônus de Agilidade às suas jogadas de Defesa.',repeatable:true,manual:true},
  {id:'aumento-atributo',name:'Aumento de Atributo',minLevel:1,description:'Escolha um dos seis atributos. Você recebe +1 nele até o máximo de +5. Pode escolher este talento quantas vezes quiser.',repeatable:true,params:['attribute'],automation:'attribute'},
  {id:'pau-toda-obra',name:'Pau pra Toda Obra',minLevel:1,description:'Você recebe permanentemente 1d4 em todos os seus testes de perícia.',repeatable:true},
  {id:'mestre-armas',name:'Mestre das Armas',minLevel:1,description:'Você pode rerrolar qualquer resultado 1 ou 2 nos dados de dano da arma ao fazer um ataque. Deve usar o novo resultado, mesmo que ele seja 1 ou 2 novamente.',repeatable:true},
  {id:'invocador',name:'Invocador',minLevel:30,description:'Quando invocar uma criatura, pode invocar uma criatura a mais.',repeatable:true},
  {id:'corpo-saudavel',name:'Corpo Saudável',minLevel:1,description:'Você tem resistência a dano de veneno e de fogo.',repeatable:true},
  {id:'duravel',name:'Durável',minLevel:1,description:'No primeiro nível e a cada 10 níveis subsequentes, você soma seu valor de Constituição ao HP uma vez a mais. Isso se soma à progressão normal de HP da sua prole.',repeatable:true,automation:'hp'},
  {id:'mestre-habilidades',name:'Mestre das Habilidades',minLevel:60,description:'Sempre que tiver Vantagem em um ataque usando uma das suas habilidades, pode rolar 3 dados e escolher o melhor, em vez dos 2 dados da Vantagem normal.',repeatable:true},
  {id:'chef',name:'Chef',minLevel:1,description:'Ao fazer um descanso curto ou longo, pode preparar uma refeição simples se tiver o equipamento necessário. Prepara para um número de criaturas igual a 2× seu bônus de proficiência; quem comer recebe 1d8 + seu bônus de proficiência em HP temporário.',repeatable:true},
  {id:'gambito-ofensivo',name:'Gambito Ofensivo',minLevel:1,description:'Ao realizar um ataque de arma, pode escolher receber −3 no acerto para causar +5 de dano.',repeatable:true},
  {id:'ataque-descuidado',name:'Ataque Descuidado',minLevel:1,description:'No início do seu turno, pode escolher atacar de forma descuidada. Você recebe Vantagem nas jogadas de ataque com armas, mas jogadas de ataque contra você também são feitas com Vantagem.',repeatable:true},
  {id:'mestre-escudos',name:'Mestre de Escudos',minLevel:1,description:'Você pode adicionar todo o seu bônus de proficiência à Defesa quando estiver empunhando um escudo, em vez de apenas metade.',repeatable:true,automation:'shield'},
  {id:'iniciado-magia',name:'Iniciado em Magia',minLevel:1,description:'Você aprende dois cantrips da lista de cantrips. Não precisa ser um conjurador para adquirir este talento.',repeatable:true},
  {id:'adepto-magico',name:'Adepto Mágico',minLevel:60,description:'Você pode ensinar as magias que possui a outro jogador adepto ao uso de magia, desde que sejam de um nível que o conjurador que está aprendendo possa conjurar.',repeatable:true}
];
